name: black workflow test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  black_checker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install black
      - name: Run Black
        run: black --check .

